- cve_id: CVE-2018-1000616
  repo: opennetworkinglab/onos
  fix: af1fa39a53c0016e92c1de246807879c16f507d6
  files:
  - drivers/utilities/src/main/java/org/onosproject/drivers/utilities/XmlConfigParser.java
- cve_id: CVE-2017-15719
  repo: sebfz1/wicket-jquery-ui
  fix: 6f33727a1b4aa27d58d672a96154d9061db43fa
  files:
  - wicket-kendo-ui/src/main/java/com/googlecode/wicket/kendo/ui/widget/editor/Editor.java
